org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
# Proxy settings
systemProp.http.proxyHost=21.0.0.83
systemProp.http.proxyPort=15004
systemProp.http.proxyUser=container_container_01MmuEcDfceBv2tT5UBu8uab--claude_code_remote--806d43
systemProp.http.proxyPassword=jwt_eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6Iks3dlRfYUVsdXIySGdsYVJ0QWJ0UThDWDU4dFFqODZIRjJlX1VsSzZkNEEifQ.eyJpc3MiOiJhbnRocm9waWMtZWdyZXNzLWNvbnRyb2wiLCJvcmdhbml6YXRpb25fdXVpZCI6ImE4ZjExZTQ2LWU0NTgtNGUzOS1iMTg5LTQ4YzEzNTdiNDUzNSIsImlhdCI6MTc3Mzk0MTYyNywiZXhwIjoxNzczOTU2MDI3LCJhbGxvd2VkX2hvc3RzIjoiKiIsImlzX2hpcGFhX3JlZ3VsYXRlZCI6ImZhbHNlIiwiaXNfYW50X2hpcGkiOiJmYWxzZSIsInVzZV9lZ3Jlc3NfZ2F0ZXdheSI6InRydWUiLCJzZXNzaW9uX2lkIjoiY3NlXzAxMjNMb2JoYzNneURrcmh6N0d5VXh4QSIsImNvbnRhaW5lcl9pZCI6ImNvbnRhaW5lcl8wMU1tdUVjRGZjZUJ2MnRUNVVCdTh1YWItLWNsYXVkZV9jb2RlX3JlbW90ZS0tODA2ZDQzIiwiZW5mb3JjZV9jb250YWluZXJfYmluZGluZyI6ImZhbHNlIn0.bgUZYwnTUJvnryM7NXtlDg24wbnCn_i3ppf-tMQx6pA_eibsdjwHKln067p0l6Oqdobl0HWtQZEEjWp3xjBE1g
systemProp.https.proxyHost=21.0.0.83
systemProp.https.proxyPort=15004
systemProp.https.proxyUser=container_container_01MmuEcDfceBv2tT5UBu8uab--claude_code_remote--806d43
systemProp.https.proxyPassword=jwt_eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6Iks3dlRfYUVsdXIySGdsYVJ0QWJ0UThDWDU4dFFqODZIRjJlX1VsSzZkNEEifQ.eyJpc3MiOiJhbnRocm9waWMtZWdyZXNzLWNvbnRyb2wiLCJvcmdhbml6YXRpb25fdXVpZCI6ImE4ZjExZTQ2LWU0NTgtNGUzOS1iMTg5LTQ4YzEzNTdiNDUzNSIsImlhdCI6MTc3Mzk0MTYyNywiZXhwIjoxNzczOTU2MDI3LCJhbGxvd2VkX2hvc3RzIjoiKiIsImlzX2hpcGFhX3JlZ3VsYXRlZCI6ImZhbHNlIiwiaXNfYW50X2hpcGkiOiJmYWxzZSIsInVzZV9lZ3Jlc3NfZ2F0ZXdheSI6InRydWUiLCJzZXNzaW9uX2lkIjoiY3NlXzAxMjNMb2JoYzNneURrcmh6N0d5VXh4QSIsImNvbnRhaW5lcl9pZCI6ImNvbnRhaW5lcl8wMU1tdUVjRGZjZUJ2MnRUNVVCdTh1YWItLWNsYXVkZV9jb2RlX3JlbW90ZS0tODA2ZDQzIiwiZW5mb3JjZV9jb250YWluZXJfYmluZGluZyI6ImZhbHNlIn0.bgUZYwnTUJvnryM7NXtlDg24wbnCn_i3ppf-tMQx6pA_eibsdjwHKln067p0l6Oqdobl0HWtQZEEjWp3xjBE1g
systemProp.http.nonProxyHosts=localhost|127.0.0.1
